### ISSUE TITLE
Dynamic add pop-up

### ISSUE THREAD

**Issue by lorenzochaudessolle** [rorystephenson/flutter_map_marker_popup#1]
We could add dynamics MarkerWithPopUp with StatefulMapController  ?

**Comment by rorystephenson** [comment]
I've done a big rewrite which makes the popups a lot more flexible now. Check out the [example](https://github.com/rorystephenson/flutter_map_marker_popup/blob/master/example/lib/main.dart) for some ideas on how to use it and let me know if you need more help!

**Comment by lorenzochaudessolle** [comment]
Your new rewrite is a very great job, i can add easily dynamics markers with pop up !

If you want some upgrade ideas, it will be very nice to have a system to pass data (not only marker) in the pop-up

**Comment by rorystephenson** [comment]
Thanks I'm really glad it works for you :).

For passing extra data that's already possible by creating a custom Marker class that extends `Marker` and adding whatever data you want to it. Then in the `popupBuilder` you can get the data off the Marker.

I've added an issue (#3) to add an example of this but in the mean time let me know if that's not clear!

**Comment by rorystephenson** [comment]
Just an update that there is now an example for this in the examples folder.

**Comment by Sanjarbek17** [comment]
Shouldn't be popup dynamic by default?
