### ISSUE TITLE
Popup is not shown

### ISSUE THREAD

**Issue by leonardoayres** [rorystephenson/flutter_map_marker_popup#10]
Hello,

I've just found your plugin and gave a try, but, unfortunately, the popup is not displayed.

After trying with Stateless widgets and "complex" layouts, I've reduced it to:

```
PopupMarkerLayerOptions(
  markers: this._markerList,
  popupSnap: PopupSnap.top,
  popupController: this._popupLayerController,
  popupBuilder: (BuildContext _, Marker marker) => Container(
	child: Text("HI"),
	color: Colors.yellow,
	width: 200,
  ),
),
```
And even that way, when I tap any marker displayed in the map, nothing happens.

Do you have any insights?

**Comment by MihailDundukov** [comment]
Hi, what did you do to fix this problem?
