### ISSUE TITLE
flutter_map_marker_popup does not "play well" with flutter_map_marker_cluster

### ISSUE THREAD

**Issue by SteveLamont** [rorystephenson/flutter_map_marker_popup#12]
First of all, the obligatory compliments and thanks for developing this nifty plugin.

I'd like to use marker clustering as well as the marker popup plugin.  However, they don't seem to interact together.

When I attempt to use both, the clustering seems to get overridden (or, perhaps, overwritten, it's difficult to tell).

**Comment by SteveLamont** [comment]
Following up on this -- I managed to work around this issue by just extending the Marker object, so no biggie if it doesn't get fixed.

In any event, it turns out that for my application, popping a Drawer was a better solution anyhow, since I have a lot of information that needs to be displayed.

**Comment by rorystephenson** [comment]
Thanks for updating and resolving this issue!

I just wanted to mention that this plugin is also integrated into the `flutter_map_marker_clustering` plugin. If you look in the config on that repo you will see options to show popups which actually use this plugin. In fact I use it this way in my personal project!

Glad to hear you found a good solution for your project!
