### ISSUE TITLE
flutter_map_marker_popup "does not show popup" when use with flutter_map_marker_cluster

### ISSUE THREAD

**Issue by zozeei** [rorystephenson/flutter_map_marker_popup#13]

**Comment by rorystephenson** [comment]
Hi @zozeei. I use them together and it seems to work fine in my project. Can you share an example which demonstrates the issue?

**Comment by zozeei** [comment]
'''
  MarkerClusterLayerOptions(
                  maxClusterRadius: 120,
                  size: Size(40, 40),
                  anchor: AnchorPos.align(AnchorAlign.center),
                  fitBoundsOptions: FitBoundsOptions(
                    padding: EdgeInsets.all(40),
                  ),
                  // markers: _isloading ? markers : [],

                  markers: [
                    MonumentMarker(
                      monument: Monument(
                        color: '#ffffff',
                        lat: 13,
                        long: 100,
                      ),
                    )
                  ],
                  polygonOptions: PolygonOptions(
                      borderColor: Colors.blueAccent,
                      color: Colors.black12,
                      borderStrokeWidth: 3),
                  builder: (context, markers) {
                    return FloatingActionButton(
                      child: Text(markers.length.toString()),
                      onPressed: null,
                    );
                  },
                ),
'''

**Comment by rorystephenson** [comment]
@zozeei The clustering plugin does not show popups by default, you need to set the `popupOptions`, see the example: https://github.com/lpongetti/flutter_map_marker_cluster/blob/02e6019dd0d60f0c7c92ceb7358104e9893b3df9/example/lib/main.dart#L142-L155

**Comment by zozeei** [comment]
@rorystephenson  thank you very much
