### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by AYJF** [rorystephenson/flutter_map_marker_popup#15]
Hello, is Null safety migration on roadmap?
Thanks you

**Comment by rorystephenson** [comment]
Hi @AYJF ! Yes it's definitely on the roadmap. I haven't started yet as I'm waiting for `flutter_map`'s null-safe release.

I haven't looked in to it but I presume it doesn't make much sense until that's done?

**Comment by rorystephenson** [comment]
#21 is basically ready (and includes some new features/improvements!). I'm just waiting for flutter_map to publish a null safe version.

In the mean time you can use the branch.

**Comment by rorystephenson** [comment]
Done! 1.0.0 is out, let me know if there are any issues :).
