### ISSUE TITLE
Popup does not pop up if marker returns a GestureDetector

### ISSUE THREAD

**Issue by barbalex** [rorystephenson/flutter_map_marker_popup#24]
This may be obvious to flutter veterans but it took me quite a while to realize that this plugin did not work for me because I had given it my standard markers that returned a GestureDetector:

```dart
Marker(
  point: latLng,
  builder: (context) => GestureDetector(
    behavior: HitTestBehavior.opaque,
    child: Icon(...),
    onTap: onTap,
  ),
)
```

Instead I have to return something else:
```dart
Marker(
  point: latLng,
  builder: (context) => Icon(...),
)
```

Might be worth adding to the readme.

Thanks for this great tool. And feel free to immediately close this issue.

**Comment by rorystephenson** [comment]
Hi @barbalex and thanks for the feedback! I'll add a note to the readme in case someone else runs in to this :).
