### ISSUE TITLE
How to add button inside popup 

### ISSUE THREAD

**Issue by killerm250m** [rorystephenson/flutter_map_marker_popup#26]
Hi, I want to add a button inside the popup, it showed without any problem but I click on the button nothing happens after some research I find that when I click on the button the map on tap event fired its like I am tapping on the map layer itself, not on the popup button.

**Comment by rorystephenson** [comment]
Hi @killerm250m, can you provide a minimal code example that demonstrates the issue?

**Comment by rorystephenson** [comment]
@killerm250m I am closing as adding a button seems to work but if I've misunderstood the request please comment and I will have another look :).
