### ISSUE TITLE
Popup not displayed

### ISSUE THREAD

**Issue by fvisticot** [rorystephenson/flutter_map_marker_popup#31]
using : 
- flutter_map 0.14.0
- flutter_map_marker_cluster 0.4.3

in the FlutterMaps layers property:

```
PopupMarkerLayerOptions(
                popupController: _checkpointPopupController,
                markerCenterAnimation: MarkerCenterAnimation(),
                markers: checkpointMarkers,
                popupBuilder: (BuildContext context, Marker marker) {
                  return ExamplePopup(marker); //CheckpointPopup(checkpoint);
                }),
```

Markers are correctly displayed but Popup is never displayed when clicking on marker.
ExamplePopup is your sample code.

Any idea ?

**Comment by rorystephenson** [comment]
I can't see anything obvious. If you provide a minimal code example I can try reproduce this myself and understand what's going wrong.

It may be related to #23 which is actually a [flutter_map issue](https://github.com/fleaflet/flutter_map/issues/1072), however I can't be sure with the example code you have shared.

**Comment by fvisticot** [comment]
Tx for your reply.
I have fixed my issue but I'm no more quite sure of what should be the best practice to integrate layers in flutter_map.

To make it works:
All the "layers" are placed in the FlutterMap children property

FlutterMap layers property was only used for the ZoomButtonsPluginOption (because no widget available for this)

Do we need to use layers or children or both and what is the logic behind ?

**Comment by rorystephenson** [comment]
No problem @fvisticot, glad you resolved your problem 👍 .

>Do we need to use layers or children or both and what is the logic behind ?

I believe that the intention is to remove the layers method of adding plugins in favour of children, see here for more info:

https://github.com/fleaflet/flutter_map/issues/1072#issuecomment-955764071

So the plugin should be migrated to be able to be added as a child.
