### ISSUE TITLE
Popup is not displayed over the Markers layer

### ISSUE THREAD

**Issue by fvisticot** [rorystephenson/flutter_map_marker_popup#32]
As we can see on the next picture, popup is not displayed on top of the marker layer. The yellow dots should be displayed behind the popup.

![image](https://user-images.githubusercontent.com/153679/145713813-451dc86b-dd4b-4af5-93d6-e593022b9c0c.png)

In the flutter_map children property, the popupLayerWidgets are displayed after the markerLayerWidget as bellow:

![image](https://user-images.githubusercontent.com/153679/145713862-ee64c70a-ee48-4aca-83be-42194474a3cc.png)

**Comment by rorystephenson** [comment]
Can you give a simplified example that I can run?

At first look I'm surprised that you have so many children layers which can support popups. MarkerClusterLayerWidget supports popups and you have two PopupMarkerLayerWidgets as well. Also PopupMarkerLayerWidget actually allows you to put markers on the map so I think you probably don't need a separate MarkerLayerWidget. See an example use of PopupMarkerLayerWidget:

https://github.com/rorystephenson/flutter_map_marker_popup/blob/3eded3b1eb26e1360d7cca7975752ec03294dfe4/example/lib/simple_map_with_popups.dart#L34-L43

**Comment by fvisticot** [comment]
Tx for the reply.
1. I have removed the useless MarkerLayerWidget

I think I understand the issue:
- I have 2 consecutives PopupMarkerLayerWidget on 2 layers
- Popups of those 2 PopupMarkerLayerWidget are not displayed on the highest layers
- So markers of the last PopupMarkerLayerWidget are visible when display popup from the previous layer

It is "only" my idea, and I hope it will give you more context


The last code looks like:

![image](https://user-images.githubusercontent.com/153679/145946871-4695e5d0-0501-4d1f-a2e9-49a82030cb52.png)

**Comment by rorystephenson** [comment]
@fvisticot thanks for the extra information. In order to dig more I will need a runnable minimal example that demonstrates the issue.

**Comment by rorystephenson** [comment]
I'm going to close this for now since I can't debug further without a runnable example, I will be happy to have another look if you can provide one.

**Comment by shahpasandar** [comment]
Any updates? I have the same issue on the version 2.1.2. The marker's popup is behind the other markers.

**Comment by rorystephenson** [comment]
As far as I know there are no bugs that cause popups to be behind markers. It is most likely an error in the way that this package is being used. Please provide a minimal example (runnable code) and I can help you out.
