### ISSUE TITLE
Show Popup out of the box?

### ISSUE THREAD

**Issue by deezaster** [rorystephenson/flutter_map_marker_popup#34]
I am so excited about this package. In particular, the actual popup window has impressed me.

I would like to call the popup outside of this package. How is this possible? Specifically, it is about the package https://pub.dev/packages/flutter_map_tappable_polyline

Unfortunately, I can't get the design right with AlertDialog's customizing. Problems also with the exact positioning of the popup.

```
TappablePolylineLayerWidget(
  options: TappablePolylineLayerOptions(
      polylineCulling: false,
      pointerDistanceTolerance: 20,
      polylines: _mapPolylines,
      onTap: (polylines, tapPosition) {
        _popupLayerController.hideAllPopups();

        /// HERE:
        MapPopupCorso.show(context, polylines.map((polyline) => polyline.tag).join(','));
      },
     ),
),
PopupMarkerLayerWidget(
  options: PopupMarkerLayerOptions(
    popupController: _popupLayerController,
    markers: _markers,
    markerRotateAlignment: PopupMarkerLayerOptions.rotationAlignmentFor(AnchorAlign.top),
    popupBuilder: (_, Marker marker) {
      if (marker is MapMarker) {
        return MapPopup(markerData: marker.markerData);
      }
      return const SizedBox();
    },
  ),
),
```

**Comment by rorystephenson** [comment]
Hi @deezaster, thanks for the interest in this plugin :).

Can you give me some more information about what is not working?

**Comment by deezaster** [comment]
Everything works perfectly! 

```
PopupMarkerLayerWidget(
  options: PopupMarkerLayerOptions(
    popupController: _popupLayerController,
    markers: _markers,
    markerRotateAlignment: PopupMarkerLayerOptions.rotationAlignmentFor(AnchorAlign.top),
    popupBuilder: (_, Marker marker) {
      if (marker is MapMarker) {
        return MapPopup(markerData: marker.markerData);
      }
      return const SizedBox();
    },
  ),
)
```

But I want to use the popup for the package flutter_map_tappable_polyline but don't know how. 

Currently I am calling an AlertDialog (customized as MapPopupCorso, see HERE in the code). But this one is ugly and is only displayed centered. I would like to use **your popup** with exact positioning.

```
TappablePolylineLayerWidget(
  options: TappablePolylineLayerOptions(
      polylineCulling: false,
      pointerDistanceTolerance: 20,
      polylines: _mapPolylines,
      onTap: (polylines, tapPosition) {
        _popupLayerController.hideAllPopups();

        /// === > HERE:
        MapPopupCorso.show(context, polylines.map((polyline) => polyline.tag).join(','));
      },
     ),
),
```

**Comment by rorystephenson** [comment]
@deezaster Ah OK I think I understand now. So it looks like you have map markers with the working popup but you _also_ want the popups to show when you tap on the polyline. If that's right then you need to have a mapping from the polyline to the marker (either stored in a `Map` or perhaps it's possible to extend polyline to have it contain a reference to a marker) then just call `_popupLayerController.showPopupsOnlyFor()` with the relevant marker.

**Comment by deezaster** [comment]
Yeah, i did it! Thanks for the support and help.

**Comment by rorystephenson** [comment]
Great I'm glad it works for you 🙂.
