### ISSUE TITLE
The argument type 'void Function(TapPosition)' can't be assigned to the parameter type 'void Function(TapPosition, LatLng)'.

### ISSUE THREAD

**Issue by nep2099** [rorystephenson/flutter_map_marker_popup#37]
Hi, I'm getting this error as noted in the title, for `onTap: (_) => _popupLayerController.hideAllPopups()`

Any idea how I could solve this issues? Many thanks in advance.

**Comment by rorystephenson** [comment]
@nep2099 Based on the error message it looks like it should be `onTap: (_, __) => _popupLayerController.hideAllPopups()`.
