### ISSUE TITLE
Popup keeps state when tapping another marker

### ISSUE THREAD

**Issue by rorystephenson** [rorystephenson/flutter_map_marker_popup#4]
Issue originally reported here: https://github.com/johnpryan/flutter_map/issues/590#issuecomment-617923323 :

>When I click on a Marker and then click on another Marker it keeps the information from the previous marker in Popup. To update the information you need to click on the map and then click on the Marker. I tried to solve it by calling hide before the change but it doesn't work.
>
>```
>popupLayerController.hidePopup(); mapController.move(LatLng(city.latitude, city.longitude), 7); >popupLayerController.togglePopup(markers[index]);
>```

**Comment by rorystephenson** [comment]
This is now fixed in 0.1.4 🙂. I also added `showPopupForMarker(Marker)` if you don't want the marker to be toggled by the PopupController.

Here's the relevant change that fixed the bug if anyone is interested: https://github.com/rorystephenson/flutter_map_marker_popup/commit/ed3ce2cd73a9169a08770b4c3c8a7ae764e27499#diff-942282e93603965e1bade94e67f446a1R80-R82

The key had to be changed when the selected marker was change so that the subtree got rebuilt.

**Comment by kekeu** [comment]
It was very good.
