### ISSUE TITLE
How to update markers dynamically

### ISSUE THREAD

**Issue by AdamF42** [rorystephenson/flutter_map_marker_popup#42]
Hello,
I want to retrieve data from a service depending on the portion of the map available on the screen. The problem is that I didn't find a way to dynamically update markers in a PopupMarkerLayerOption. 
Should I use the "rebuild" property? If so, do you have any usage examples?

Thank you

**Comment by rorystephenson** [comment]
This sounds a bit out of the scope of this plugin to be quite honest. This plugin is based on the built-in flutter_map MarkerLayer code which, afaik, does not support this. I'm open to PRs if you want to have a go.
