### ISSUE TITLE
Bump flutter_map to 1.0.0

### ISSUE THREAD

**Issue by eliabieri** [rorystephenson/flutter_map_marker_popup#44]
Bump flutter_map to latest version

**Comment by JaffaKetchup** [comment]
Hi @rorystephenson,
If you want to join the discord just because or you want to offer more support to users, just join using the link and ping me and I'll give you the plugin maintainer role :)
Many thanks!

**Comment by pablojimpas** [comment]
I've created a PR to adopt the new plugin API, the code changes were minimal and really straightforward. Feel free to review it and release a new version, this issue is blocking https://github.com/lpongetti/flutter_map_marker_cluster/issues/119

**Comment by rorystephenson** [comment]
> Hi @rorystephenson, If you want to join the discord just because or you want to offer more support to users, just join using the link and ping me and I'll give you the plugin maintainer role :) Many thanks!

Awesome :). I've joined and my handle is Rory#5938.
