### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by hiroppi401** [rorystephenson/flutter_map_marker_popup#52]
when popup window opened then dragging map, the popup builder triggered? 
![Screenshot_2022-08-08_02-30-05](https://user-images.githubusercontent.com/48790378/183308028-9a53c605-3f9a-4af9-94b7-bb7582c0b522.png)

**Comment by rorystephenson** [comment]
Hi @hiroppi401 . If you extract out the builder in to a separate widget I believe this won't happen. In any case it's normal for flutter to build widgets multiple times and flutter is optimised for that.
