### ISSUE TITLE
MarkerTapBehavior.togglePopupAndHideRest doesnt work as expected

### ISSUE THREAD

**Issue by Pepslee** [rorystephenson/flutter_map_marker_popup#54]
Hi.
MarkerTapBehavior.togglePopupAndHideRest doesnt work as expected.
When I tap to the Marker popUp is appear, but when I tap one more time to that marker, popUp doesnt dissapear.

popupState.selectedMarkers is always empty and contains(marker) is always return false

This was tested for the example code of the flutter_map_marker_cluster

**Comment by rorystephenson** [comment]
I've just tried this in the example and it seems to work fine for me. Did you make any changes to the example? Make you can make a video or give me more details to be able to reproduce it?

**Comment by rorystephenson** [comment]
No problem, I will close the issue here as I see there is one open on `flutter_map_marker_cluster`.
