### ISSUE TITLE
How to adjust popup snap for map rotation

### ISSUE THREAD

**Issue by samstamper33** [rorystephenson/flutter_map_marker_popup#56]
Hi all - 

I'm using popupsnap.mapBottom, but the popup moves up and down based on the rotation of the map. Is there a way to snap this to the bottom of the container holding FlutterMap?

<img width="340" alt="Screenshot 2023-03-03 at 12 36 22 PM" src="https://user-images.githubusercontent.com/120147816/222800645-659128b3-2c47-467c-a859-f0bf1632e7d0.png">
<img width="346" alt="Screenshot 2023-03-03 at 12 35 56 PM" src="https://user-images.githubusercontent.com/120147816/222800651-98b73f0a-ce46-4e89-9208-a5fd67e5c163.png">

**Comment by rorystephenson** [comment]
There was a regression in the last version 🤦  , I've just published 4.0.1 which should fix this. Sorry!
