### ISSUE TITLE
How to add a pin below the Popup Panel anchored at it's marker just like google earth?

### ISSUE THREAD

**Issue by 244226077** [rorystephenson/flutter_map_marker_popup#6]
How to add a pin below the Popup Panel anchored at it's marker just like google earth? This will help if there is a mass of markers because I can kown exactly which marker the Popup Pane is linked.

**Comment by rorystephenson** [comment]
Hi @244226077, can you provide an image that shows what you mean?

**Comment by 244226077** [comment]
> Hi @244226077, can you provide an image that shows what you mean?

@rorystephenson 
![aaaa](https://user-images.githubusercontent.com/33371469/84058869-629c2e00-a9ec-11ea-9490-108b9d24bffe.jpg)

**Comment by Dereumaux-Adrien** [comment]
Hi @244226077 You could put your custom in a column with a triangle that you can create following this SE answer: https://stackoverflow.com/a/56945726/4791411

**Comment by rorystephenson** [comment]
Agreed with @Dereumaux-Adrien that this can be implemented by the widget you decide to use for the popup!

It would be nice to have an example for this but I don't have the time right now.

Closing but feel free to ask again if you don't manage to get this working!

**Comment by Dereumaux-Adrien** [comment]
I found out how to later, you add clippy_flutter and then this in a column after your container:
```
Triangle.isosceles(
  edge: Edge.BOTTOM,
  child: Container(
    color: Colors.blue,
    width: 20.0,
    height: 10.0,
  ),
)
```

**Comment by rorystephenson** [comment]
Great @Dereumaux-Adrien 👏 !
