### ISSUE TITLE
Can't use along flutter_map ^4.0.0

### ISSUE THREAD

**Issue by Richard-Walter** [rorystephenson/flutter_map_marker_popup#60]
If i try to use this plugin along with flutter map ^4.0.0 i get the following error when getting packages:

Because flutter_map_marker_popup 4.0.3 depends on flutter_map ^3.1.0 and no versions of flutter_map_marker_popup match >4.0.3 <5.0.0, flutter_map_marker_popup ^4.0.3 requires flutter_map ^3.1.0.
So, because fsd_desktop depends on both flutter_map ^4.0.0 and flutter_map_marker_popup ^4.0.3, version solving failed.
pub get failed

**Comment by rorystephenson** [comment]
4.1.0 now supports this.
