### ISSUE TITLE
marker popup not above other markers

### ISSUE THREAD

**Issue by Richard-Walter** [rorystephenson/flutter_map_marker_popup#61]
Thanks for your great little package mate.  However, I have one undersirable issue. 

I have two sepearate marker layers - airports and POIs.  The issue is that the airport  popup window is showing the poi map markers from the map on the popup window (see screenshot).

    children: <Widget>[
        TileLayer(
          urlTemplate: ref.watch(fsdMapLayerStateProvider),
          subdomains: const ['a', 'b', 'c'],
        ),
        const FlightPlanPolylineWidget(),
        Visibility(
          visible: showFlightsChecked,
          child: const FlightPolygonWidget(),
        ),
        Visibility(
          visible: showFlightsChecked,
          child: const FlightPolylineWidget(),
        ),
        const PoiMarkersWidget(),
        const AirportMarkersWidget(),
      ],

`![](https://cdn.discordapp.com/attachments/978697778031112242/1104197863468171275/dssdf.jpg)

I could reverse the order of the Poi and Airport markers widgets but i just get the same issue except the airports markers show on the Poi Popup window.

It also very difficult for me to combine these markers -  The PoiMarkersWidget widget uses the supercluster plugin, whilst the AirportMarkersWidget doesnt  and the airport markers are only visible at a certain zoom level.   Basically, messy and difficult to combine these markers.  

How can we make the popup window to be above everything else on the map.?  I think that any popup window   should be above all other map layers.

**Comment by rorystephenson** [comment]
> Thanks for your great little package mate.

You're very welcome 🙂.

> I could reverse the order of the Poi and Airport markers widgets but i just get the same issue except the airports markers show on the Poi Popup window.
> 
> It also very difficult for me to combine these markers - The PoiMarkersWidget widget uses the supercluster plugin, whilst the AirportMarkersWidget doesnt and the airport markers are only visible at a certain zoom level. Basically, messy and difficult to combine these markers.
> 
> How can we make the popup window to be above everything else on the map.? I think that any popup window should be above all other map layers.

Right I can see how combining the markers is tricky here. It makes sense to be able to control where the popups are displayed independent of the markers. I am having a look in to how this can work.

**Comment by rorystephenson** [comment]
Hi @Richard-Walter, it is now possible to do as you requested in the latest version. See the new added example in flutter_map_supercluster. Let me know if you run in to any issues!

**Comment by Richard-Walter** [comment]
Thanks mate....that worked like a charm!
