### ISSUE TITLE
Update latlong2 to 0.9.0

### ISSUE THREAD

**Issue by flodaniel** [rorystephenson/flutter_map_marker_popup#62]
LatLong2 published new major version, which this package should support: https://pub.dev/packages/latlong2/changelog

**Comment by rorystephenson** [comment]
I'm working on a large set of changes to make #61 possible, amongst other things. I will first release that with the same latlong2 version and shortly after will work on migrating to dart 3 which latlong2 0.9.0 requires.

**Comment by flodaniel** [comment]
Cool! Thank you for your effort! 🚀

**Comment by rorystephenson** [comment]
So releasing a dart 3 compatible version can be done but flutter_map needs to publish a version with latlong2 0.9.0 before I can bump latlong2 in this package. There is a version 5 prelease but I will wait for a proper release.

**Comment by niku** [comment]
Hi, [flutter_map v5.0 was released](https://pub.dev/packages/flutter_map/versions/5.0.0) yesterday.
So, it seems you don't have to keep latlong2 0.8 any longer 👋

**Comment by rorystephenson** [comment]
Thanks for the heads-up. I've posted [a comment](https://github.com/fleaflet/flutter_map/pull/1532#pullrequestreview-1466723876) on the 5.0 PR about one change which affects this plugin, once we have determine whether a further change occurs or not I will release a new version.

**Comment by Felipe-N0bre** [comment]
https://github.com/fleaflet/flutter_map/pull/1532#pullrequestreview-1466723876 has been merged, any prevision when we   can have this update? Thanks!

**Comment by rorystephenson** [comment]
@Felipe-N0bre that PR is where I commented on the change, the issue discussing a fix is here: https://github.com/fleaflet/flutter_map/issues/1552

**Comment by elliotnash** [comment]
I see that the fix is targeting flutter map v6 - will we have a version of marker popup for v5 (even if performacne is worse) or do we need to wait until flutter map v6 is released?

**Comment by rorystephenson** [comment]
> I see that the merged fix is targeting flutter map v6 - will we have a version of marker popup for v5 (even if performance is worse) or do we need to wait until flutter map v6 is released?

Hi @elliotnash , I will try to get time in the next couple of days to release a version for v5.

**Comment by rorystephenson** [comment]
Thanks for the patience everyone, 5.2.0 is now released which supports flutter_map v5 and latlong2 0.9.0.
