### ISSUE TITLE
Conflicts with plugin flutter_map_location_marker

### ISSUE THREAD

**Issue by dfrobese** [rorystephenson/flutter_map_marker_popup#63]
Hi,

I would like to  use your plugin, but it conflicts with the flutter_map_location_marker plugin.
When your plugin is lower in the child widget stack, the flutter_map_location_marker grabs the gestures first and no pupup is shown.

When your widget is top, the markes are hiding the location marker, which doesn't look nice.

Any ideas?

**Comment by rorystephenson** [comment]
Hi @dfrobese, if you don't need the location marker to be tappable you should be able to wrap that layer with an IgnorePointer.

**Comment by dfrobese** [comment]
Worked! Thanks for the advice.
