### ISSUE TITLE
method to check whether popup is showing or not

### ISSUE THREAD

**Issue by TheReprator** [rorystephenson/flutter_map_marker_popup#65]
First of all, 

thanks for this library, is there any way i can know,  whether popup is showing or not, as i know, a method exist there but i can compare it to check whether  popup is dismissed or showing.

like nPopupEvent: (event, selectedMarkers) {}

here event  is a sealed, and i am not able to use it know, whehter it is showing or hiding.

Regards,
Vikram Singh

**Comment by rorystephenson** [comment]
Hi @TheReprator, yes this is possible. See: https://pub.dev/documentation/flutter_map_marker_popup/latest/flutter_map_marker_popup.extension_api/PopupState/isSelected.html

You can also get a list of the selected markers (selected means they have a popup showing), you can see how this is used in the example: https://github.com/rorystephenson/flutter_map_marker_popup/blob/1c88a84a877e71fc98e0a1845f47125f9ff369da/example/lib/popup_outside_of_map.dart#L114

**Comment by TheReprator** [comment]
@rorystephenson apology, i hadn't gone through that, but after using this, i am getting following error,

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:provider/src/provider.dart': Failed assertion: line 274 pos 7: 'context.owner!.debugBuilding ||
E/flutter (12245):           listen == false ||
E/flutter (12245):           debugIsInInheritedProviderUpdate': Tried to listen to a value exposed with provider, from outside of the widget tree.
E/flutter (12245): 
E/flutter (12245): This is likely caused by an event handler (like a button's onPressed) that called
E/flutter (12245): Provider.of without passing `listen: false`.
E/flutter (12245): 
E/flutter (12245): To fix, write:
E/flutter (12245): Provider.of<PopupState?>(context, listen: false);
E/flutter (12245): 
E/flutter (12245): It is unsupported because may pointlessly rebuild the widget associated to the
E/flutter (12245): event handler, when the widget tree doesn't care about the value.
E/flutter (12245): 
E/flutter (12245): The context used was: ScreenMap(state: _ScreenMapState#1523c)`

Repo:  https://github.com/TheReprator/flutter_map_tracking/blob/marker_bug/lib/screens/screen_map.dart

**Comment by rorystephenson** [comment]
@TheReprator Try `PopupState.maybeOf(context, listen:false)!.selectedMarkers`

**Comment by TheReprator** [comment]
@rorystephenson 
`PopupState.maybeOf(context, listen: false)?.selectedMarkers`

it is always returning null,  whether marker is clicked or not, on tap of map.

**Comment by rorystephenson** [comment]
> @rorystephenson `PopupState.maybeOf(context, listen: false)?.selectedMarkers`
> 
> it is always returning null, whether marker is clicked or not, on tap of map.

That's odd, can you share a minimal reproducible example?

**Comment by rorystephenson** [comment]
@TheReprator I just had a quick look at your repo and you don't seem to be using PopupScope. PopupState is available from a child of PopupMarkerLayer. If you need to access the PopupState from a widget which is not a child of PopupMarkerLayer you need to raise the state up by wrapping a parent widget, for example Scaffold, in a PopupScope. Then you can call PopupState.of(context) using the context from a descendant widget of PopupScope.
