### ISSUE TITLE
FM v6 is coming soon

### ISSUE THREAD

**Issue by JaffaKetchup** [rorystephenson/flutter_map_marker_popup#70]
The next version of flutter_map is coming soon, with breaking changes for all users and plugins!

Expected CHANGELOG: https://github.com/fleaflet/flutter_map/blob/release-prep/CHANGELOG.md
Likely to be merged PR with significant impacts: fleaflet/flutter_map#1615
Release prep PR: fleaflet/flutter_map#1632
New documentation (path liable to change): https://docs.fleaflet.dev/v/v6-1
Expected migration instructions, suitable for most users: https://docs.fleaflet.dev/v/v6-1/getting-started/migrating-to-v6
List of commits since v5 (more to come): https://github.com/fleaflet/flutter_map/compare/v5.0.0...master

**Comment by Eimji** [comment]
Hello,

flutter_map v6 is now released.

An update for flutter_map v6 please !!!

**Comment by rorystephenson** [comment]
Wow I just started having a look... it's going to take time. There is a TON of breaking changes, way more than I would expect for a single major version.

**Comment by JaffaKetchup** [comment]
We hope you like the new look, and welcome any feedback!
