### ISSUE TITLE
Import conflict for LatLngTween with flutter_map 6.0.1

### ISSUE THREAD

**Issue by tijee** [rorystephenson/flutter_map_marker_popup#72]
When compiling with flutter_map **_6.0.1_** there is a build error:

`.pub-cache/hosted/pub.dev/flutter_map_marker_popup-6.1.1/lib/src/marker_layer.dart:136:19: Error: 'LatLngTween' is imported from both 'package:flutter_map/src/gestures/latlng_tween.dart' and 'package:flutter_map_marker_popup/src/lat_lng_tween.dart'.`

which makes sense because `marker_layer.dart` imports both `package:flutter_map_marker_popup/src/lat_lng_tween.dart` and `package:flutter_map/flutter_map.dart`, which in turn exports `package:flutter_map/src/gestures/latlng_tween.dart` since the very last version (6.0.1).

With flutter_map 6.0.0 it's fine.

**Comment by rorystephenson** [comment]
Thank you for raising the issue. @adouglass opened a PR with a fix and I have merged that (along with a couple of other minor version bumps) and released 6.1.2.
