### ISSUE TITLE
How to get a popup to follow a marker when it moves?

### ISSUE THREAD

**Issue by asmith26** [rorystephenson/flutter_map_marker_popup#74]
Hi there,

Is it possible to get a popup to follow a marker when it moves?

I've an adapted the [basic example](https://github.com/rorystephenson/flutter_map_marker_popup/blob/master/example/lib/basic_example_page.dart) as a minimal reproducible example:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map_marker_popup/flutter_map_marker_popup.dart';
import 'package:latlong2/latlong.dart';

import 'example_popup.dart';

class BasicExamplePage extends StatefulWidget {
  static const route = 'basicExamplePage';
  const BasicExamplePage({Key? key}) : super(key: key);
  @override
  BasicExamplePageState createState() => BasicExamplePageState();
}

class BasicExamplePageState extends State<BasicExamplePage> {
  static List<Marker> _markers = [const LatLng(44.421, 10.404)]
      .map(
        (markerPosition) => Marker(
      point: markerPosition,
      width: 40,
      height: 40,
      alignment: Alignment.topCenter,
      child: const Icon(Icons.location_on, size: 40),
    ),
  )
      .toList();

  @override
  Widget build(BuildContext context) => Scaffold(
    floatingActionButton:FloatingActionButton(
        child: Icon(Icons.gps_fixed),
        onPressed: () async {
          _markers = await getLocation();
          setState(() {});
        }),
    body: FlutterMap(
      options: const MapOptions(
        initialZoom: 5.0,
        initialCenter: LatLng(44.421, 10.404),
      ),
      children: [
        TileLayer(
          urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
        ),
        PopupMarkerLayer(
          options: PopupMarkerLayerOptions(
            markers: _markers,
            popupDisplayOptions: PopupDisplayOptions(
              builder: (BuildContext context, Marker marker) =>
                  ExamplePopup(marker),
            ),
          ),
        ),
      ],
    ),
  );

  getLocation() => [LatLng(45.246, 5.783)]      .map(
          (markerPosition) => Marker(
        point: markerPosition,
        width: 40,
        height: 40,
        alignment: Alignment.topCenter,
        child: const Icon(Icons.location_on, size: 40),
      )).toList();
}
```

And here is the current problem I'm seeing where the popup doesn't move with the marker:

![](https://github.com/rorystephenson/flutter_map_marker_popup/assets/6988036/fd639453-9a3d-4d7a-b36c-947203f7bd16)

![](https://github.com/rorystephenson/flutter_map_marker_popup/assets/6988036/26aedbc3-6ee6-4a75-b32a-850e30728f6c)

Many thanks for any help, and for this amazing lib! :)

**Comment by translibrius** [comment]
I am facing a similar issue where my markers move because that's live user data, however if a popup was open and rebuild happens, the popup stays in the old position, I have to close it and press on the new location of the marker for it be in the correct spot. 

Should I be closing all popups programmatically every time and reopening in the new spot or something?

Thanks for the lib btw, it's awesome!

**Comment by rorystephenson** [comment]
Unfortunately I'm not sure this is going to be very easy to do. This plugin works by creating a separate layer and when you open a popup it has a fixed point. I think popups following markers is probably quite a separate use-case that should have a dedicated plugin.

**Comment by omarbenzekri** [comment]
Hi
  Please,Did you find any solution,I'm facing the same issue.
@asmith26  @translibrius.

**Comment by asmith26** [comment]
I haven't I'm afraid.

**Comment by fvisticot** [comment]
Same issue. any update ?
