### ISSUE TITLE
How to create Draggable PopupMarker

### ISSUE THREAD

**Issue by S-Man42** [rorystephenson/flutter_map_marker_popup#75]
Hi,

i've been using this plugin since early versions. Now I found a bug in my map tool. 

Previously I was able to drag a PopupMarker by creating the marker by having a builder like this:

```
builder: (context) {
  return GestureDetector(
      onPanUpdate: (DragUpdateDetails details) {
        _popupLayerController.hidePopup();
        // some calculations for positioning  ...
      },
      child: icon,
    );
}
```

It worked fine until Flutter Map 3 and with flutter_map_marker_popup version 4.0.3

Now I did the major updater to FlutterMap 5 and your version 5.2.0 and I cannot pan anymore. The `onPanUpdate` event is not called anymore for my `GestureDetector`. Funny enough: All other events work like `onTap` and even `onVerticalDragUpdate`.

I cannot figure out what changed but I guess it is due to the breaking changes of your plugin. Do you have an idea?

Kind regards!

**Comment by rorystephenson** [comment]
Hi @S-Man42 . Unfortunately I don't have a lot of time to dig in to this right now. If you do manage to get to the bottom of why this is not working for you and figure out a fix I'd be happy to merge it in.
