### ISSUE TITLE
The app was built, but the map is not working.

### ISSUE THREAD

**Issue by abinash1220** [rorystephenson/flutter_map_marker_popup#76]
Hi bro, I cloned your project, then modified the latitude and longitude values and built the app. When I opened the map, it was not working. What is the issue? Please guide me, bro.

**Comment by rorystephenson** [comment]
Hi @abinash1220 . I've just tried out the example in the latest release and it is working fine. Please try out 7.0.0 and if that's not working then provide a minimal reproducible example of the map not working for you.
