### ISSUE TITLE
Question: how this can be adapted to work with mapbox_maps_flutter?

### ISSUE THREAD

**Issue by wwyung** [rorystephenson/flutter_map_marker_popup#77]
Liked your library very much, but unfortunately I am currently stuck with mapbox_maps_flutter, if you can give me some suggestions on what APIs I need in order to port this over to support mapbox_maps_flutter, I can take a stab at it. Thank you!

**Comment by rorystephenson** [comment]
Hi @wwyung . This plugin is quite closely tied to the inner workings of flutter_map. So I'm not sure that's going to be an easy feat. I think you'd be better served creating a plugin from scratch for mapbox and maybe copying some code from this plugin where it can be useful (i.e. popup positioning calculations).
