### ISSUE TITLE
popupBuilder called on map move

### ISSUE THREAD

**Issue by Swepilot** [rorystephenson/flutter_map_marker_popup#9]
If a popup is open, every map move will cause the popupBuilder to be called. Is there a way to prevent this?

In my case, when the popup is build I get data from a local database (which can be a lot) so then if I move the map with the popup open, the database gets called and the dataset processed again, over and over. This slows down performance.

**Comment by rorystephenson** [comment]
@Swepilot Hmm that's probably expected due to the way flutter works. Moving a widget will always cause it to rebuild I think. If you share your popupBuilder implementation maybe I can suggest a way to avoid having the data reloaded every rebuild?

**Comment by Swepilot** [comment]
Of course, silly me... Blaming a few months of no coding. I changed the widget into a StatefulWidget and moved the data fetching code into initState. Thanks for the quick feedback though!
